print('please enter the number of business sales out of 100(percentage) you have in these five countries:')
England=float(input('England:'))
India=float(input('India:'))
USA=float(input('USA:'))
China=float(input('China:'))
Spain=float(input('Spain:'))
sum=England+India+USA+China+Spain
print('The sum of the of sales in these 5 countries are about',sum,' out of 500')
summ=int(sum)
print('The rough sum of the of sales in these 5 countries are about',summ,' out of 500')
Av=float(sum/5)
print('The average of your percentage of sales is',Av,'% per country')
Avv=int(Av)
print('The rough average/percentage mark of your total business sales is',Avv,'% per country')